### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by InnoraG** [codeforequity-at/botium-connector-fbwebhook#9]
Hello

First of all, great idea about the library

All works well but facing issue in this connector

It can't be loaded

This is the log

```

Debugger attached.
2021-05-23T12:12:59.564Z botium-cli Using Botium configuration file E:\MyDoc\DevProjects\botium-testing\botium-cli\botium-botkit-facebook.json
2021-05-23T12:12:59.570Z botium-core-BotDriver Loaded Botium configuration files E:\MyDoc\DevProjects\botium-testing\botium-cli\botium-botkit-facebook.json
Crawler started...
2021-05-23T12:12:59.906Z botium-crawler-crawler A crawler started with the following params:
      entryPoints: ["qrpayload"],
      depth: 5,
      numberOfWelcomeMessages: 0,
      exitCriteria: [],
      waitForPrompt: 1000,
      userAnswers: []
2021-05-23T12:12:59.906Z botium-core-BotDriver Build - Botium Core Version: 1.11.3
2021-05-23T12:12:59.909Z botium-core-BotDriver Build - Capabilites: {
  PROJECTNAME: '2021botkitfacebooktest',
  TESTSESSIONNAME: 'Botium Test Session',
  TESTCASENAME: 'Botium Test Case',
  TEMPDIR: 'botiumwork',
  CLEANUPTEMPDIR: true,
  WAITFORBOTTIMEOUT: 10000,
  SIMULATE_WRITING_SPEED: false,
  SIMPLEREST_PING_RETRIES: 6,
  SIMPLEREST_PING_TIMEOUT: 10000,
  SIMPLEREST_PING_VERB: 'GET',
  SIMPLEREST_PING_UPDATE_CONTEXT: true,
  SIMPLEREST_PING_PROCESS_RESPONSE: false,
  SIMPLEREST_STOP_RETRIES: 6,
  SIMPLEREST_STOP_TIMEOUT: 10000,
  SIMPLEREST_STOP_VERB: 'GET',
  SIMPLEREST_START_RETRIES: 6,
  SIMPLEREST_START_TIMEOUT: 10000,
  SIMPLEREST_START_UPDATE_CONTEXT: true,
  SIMPLEREST_START_PROCESS_RESPONSE: true,
  SIMPLEREST_START_VERB: 'GET',
  SIMPLEREST_POLL_VERB: 'GET',
  SIMPLEREST_POLL_INTERVAL: 1000,
  SIMPLEREST_POLL_UPDATE_CONTEXT: true,
  SIMPLEREST_METHOD: 'GET',
  SIMPLEREST_IGNORE_EMPTY: true,
  SIMPLEREST_TIMEOUT: 10000,
  SIMPLEREST_EXTRA_OPTIONS: {},
  SIMPLEREST_STRICT_SSL: true,
  SIMPLEREST_INBOUND_UPDATE_CONTEXT: true,
  SIMPLEREST_CONTEXT_MERGE_OR_REPLACE: 'MERGE',
  SCRIPTING_TXT_EOL: '\n',
  SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  SCRIPTING_XLSX_HASHEADERS: true,
  SCRIPTING_CSV_SKIP_HEADER: true,
  SCRIPTING_CSV_QUOTE: '"',
  SCRIPTING_CSV_ESCAPE: '"',
  SCRIPTING_NORMALIZE_TEXT: true,
  SCRIPTING_ENABLE_MEMORY: false,
  SCRIPTING_ENABLE_MULTIPLE_ASSERT_ERRORS: false,
  SCRIPTING_MATCHING_MODE: 'wildcardIgnoreCase',
  SCRIPTING_UTTEXPANSION_MODE: 'all',
  SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  SCRIPTING_UTTEXPANSION_NAMING_MODE: 'justLineTag',
  SCRIPTING_UTTEXPANSION_NAMING_UTTERANCE_MAX: '16',
  SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
  SCRIPTING_FORCE_BOT_CONSUMED: false,
  ASSERTERS: [],
  LOGIC_HOOKS: [],
  USER_INPUTS: [],
  SECURITY_ALLOW_UNSAFE: true,
  CONTAINERMODE: 'fbwebhook',
  FBWEBHOOK_WEBHOOKURL: 'http://localhost:3123/api/facebook',
  SIMPLEREST_INBOUND_REDISURL: 'redis://localhost:6379',
  CONFIG: 'E:\\MyDoc\\DevProjects\\botium-testing\\botium-cli\\botium-botkit-facebook.json'
}
2021-05-23T12:12:59.910Z botium-core-BotDriver Build - Sources : { LOCALPATH: '.', GITPATH: 'git', GITBRANCH: 'master', GITDIR: '.' }
2021-05-23T12:12:59.910Z botium-core-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true }
2021-05-23T12:13:07.243Z botium-core-BotDriver BotDriver Build error: Error: Loading Botium Plugin failed.
Loading Botium plugin from fbwebhook failed - Cannot find module 'fbwebhook'
Require stack:
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\src\run\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\bin\botium-cli.js
Loading Botium plugin botium-connector-fbwebhook failed, try "npm install botium-connector-fbwebhook" - Cannot call a class as a function
Botium-Crawler failed:  Error: Loading Botium Plugin failed.
Loading Botium plugin from fbwebhook failed - Cannot find module 'fbwebhook'
Require stack:
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\src\run\index.js
- e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\bin\botium-cli.js
Loading Botium plugin botium-connector-fbwebhook failed, try "npm install botium-connector-fbwebhook" - Cannot call a class as a function
    at tryLoadPlugin (e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\src\containers\plugins\index.js:133:9)
    at PluginConnectorContainer.Validate (e:\MyDoc\DevProjects\cloned-botkit-cli\botium-cli\node_modules\botium-core\src\containers\PluginConnectorContainer.js:14:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Waiting for the debugger to disconnect...


```

Thanks

**Comment by codeforequity-at** [comment]
Pls describe the steps you took before running into this

**Comment by InnoraG** [comment]
git clone https://github.com/codeforequity-at/botium-cli.git
cd botium-cli
npm i
npm i botium-crawler botium-connector-fbwebhook
node bin\botium-cli.js crawler-run

this is the botium.json
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "githubissue",
      "CONTAINERMODE": "fbwebhook",
      "FBWEBHOOK_WEBHOOKURL": "http://localhost:3123/api/facebook",
      "SIMPLEREST_INBOUND_REDISURL": "redis://localhost:6379",
      "FBWEBHOOK_APPSECRET": "xxxxxxxxxx"
    }
  }
}

**Comment by InnoraG** [comment]
However , managed to resolve
.babelrc file needs to be removed before re-build

Thanks for fantastic reactivity !
